CMake: Generate a config.redo script in per-repo build dirs
Before we only generated a 'config.redo' script in the build dir of
qtbase or a top-level build. After this change, we will also generate
one when configuring repos in a per-repo build of qt.

This allows quick fresh reconfiguration of a repo, without having to
remember how it was configured before.

To make that happen, we need to duplicate parts of the '-redo' code
that was initially added in configure, into qt-configure-module, both
for the Unix and Windows scripts.

Slight adjustments had to be made to account for the source repo path
argument, that needs to be skipped from being added into the
config.opt.in file.

We also need to modify the code that generates the config.redo file to
do it at the start of each repo configuration, rather than just when
configuring qtbase.

Amends 8ffb6ce64cb0183bf6805497b398463549c1ed8d

Change-Id: I76cd5296ea23ca5bfef6b8975c82416b628bc5d1
Reviewed-by:  Alexey Edelev <alexey.edelev@qt.io>

diff --git a/bin/qt-configure-module.in b/bin/qt-configure-module.in
--- a/bin/qt-configure-module.in
+++ b/bin/qt-configure-module.in
@@ -4,6 +4,39 @@ set -eu
 script_dir_path=`dirname $0`
 script_dir_path=`(cd "$script_dir_path"; pwd)`
 
+# the current directory is the "build tree" or "object tree"
+outpath=`pwd`
+outpathPrefix=$outpath
+
+SAVED_IFS=$IFS
+IFS='
+'
+
+optfile=""
+determineOptFilePath()
+{
+> "${outpathPrefix}/config.redo.in"
+set -f  # suppress globbing in for loop
+for i in "$@"; do
+    if [ x"$i" = x"-top-level" ]; then
+        continue
+    fi
+    case $i in
+        -redo|--redo)
+            optfile=${outpathPrefix}/config.opt
+            if ! test -f "$optfile"; then
+                echo >&2 "No config.opt present - cannot redo configuration."
+                exit 1
+            fi
+            ;;
+        *)
+            # If redo-ing, write the rest of parameters into the config.redo.in file
+            echo \"$i\" >> "${outpathPrefix}/config.redo.in"
+            ;;
+    esac
+done
+}
+
 printUsage()
 {
     cat <<EOF
@@ -19,6 +52,7 @@ if [ "$#" -lt 1 ]; then
     exit 1
 fi
 module_root=$1
+# This ensures the repo path does not end up in the config.opt file.
 shift
 
 if [ ! -f "$module_root/CMakeLists.txt" ]; then
@@ -27,12 +61,40 @@ if [ ! -f "$module_root/CMakeLists.txt" ]; then
     exit 1
 fi
 
-optfile=config.opt
-echo > "$optfile"
-for arg in "$@"; do
-echo "$arg" >> "$optfile"
-done
+determineOptFilePath "$@"
+
+optfilepath=${outpathPrefix}/config.opt
+opttmpfilepath=${outpathPrefix}/config.opt.in
+
+redofilepath=${outpathPrefix}/config.redo.last
+redotmpfilepath=${outpathPrefix}/config.redo.in
+
+qt_cmake_private_path="$script_dir_path/../libexec"
+
+fresh_requested_arg=
+if [ -z "$optfile" ]; then   # only write optfile if not currently redoing
+    > "$opttmpfilepath"
+    > "$redotmpfilepath"
+
+    for arg in "$@"; do echo \"$arg\" >> "$opttmpfilepath"; done
+
+    "$qt_cmake_private_path/qt-cmake-private" -DIN_FILE="${opttmpfilepath}" \
+        -DOUT_FILE="${optfilepath}" \
+        -P "$script_dir_path/@__relative_path_to_cmake_scripts_dir@/QtWriteArgsFile.cmake"
+else
+    # Rewriting config.opt into config.opt.in anyway. Allows for direct manipulation of config.opt
+    > "$opttmpfilepath"
+    for arg in `cat $optfile`; do echo \"$arg\" >> "$opttmpfilepath"; done
+
+    "$qt_cmake_private_path/qt-cmake-private" -DIN_FILE="${opttmpfilepath}" \
+        -DREDO_FILE="${redotmpfilepath}" -DOUT_FILE="${redofilepath}" \
+        -P "$script_dir_path/@__relative_path_to_cmake_scripts_dir@/QtWriteArgsFile.cmake"
+    optfilepath=${redofilepath}
+    fresh_requested_arg=-DFRESH_REQUESTED=TRUE
+fi
 
 cmake_script_path="$script_dir_path/@__relative_path_to_cmake_scripts_dir@/QtProcessConfigureArgs.cmake"
-qt_cmake_private_path="$script_dir_path/../libexec"
-"$qt_cmake_private_path/qt-cmake-private" -DOPTFILE=$optfile -DMODULE_ROOT="$module_root" -DCMAKE_COMMAND="$qt_cmake_private_path/qt-cmake-private" -P "$cmake_script_path"
+"$qt_cmake_private_path/qt-cmake-private" -DOPTFILE=$optfilepath -DMODULE_ROOT="$module_root" \
+    -DCMAKE_COMMAND="$qt_cmake_private_path/qt-cmake-private" -P "$cmake_script_path"
+
+IFS=$SAVED_IFS
