do not silently accept -separate-debug-info -static
these options are mutually exclusive.

Change-Id: Ia401edc543a2c2a111798fb4de4db453762efb64
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@digia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3441,7 +3441,11 @@ if [ "$CFG_PRECOMPILE" = "auto" ]; then
 fi
 
 # auto-detect support for separate debug info in objcopy
-if [ "$CFG_SEPARATE_DEBUG_INFO" != "no" ] && [ "$CFG_SHARED" = "yes" ]; then
+if [ "$CFG_SEPARATE_DEBUG_INFO" = "yes" ]; then
+    if [ "$CFG_SHARED" = "no" ]; then
+        echo "ERROR: -separate-debug-info is incompatible with -static"
+        exit 1
+    fi
     TEST_OBJCOPY=`getXQMakeConf QMAKE_OBJCOPY`
     COMPILER_WITH_FLAGS="$TEST_COMPILER $TEST_COMPILER_CXXFLAGS"
     if "$unixtests/objcopy.test" "$COMPILER_WITH_FLAGS" "$TEST_OBJCOPY" "$OPT_VERBOSE"; then
