Make HarfBuzz-NG the default shaper on all platforms
[ChangeLog][Important Behavior Changes] HarfBuzz-NG is now the default
shaper on all platforms. This results in a better shaping results
for various languages, better performance, and lower memory consumption.

Task-number: QTBUG-18980
Change-Id: I4d9454fc37e9050873df3857e52369dfc7f191b2
Reviewed-by: Eskil Abrahamsen Blomfeldt <eskil.abrahamsen-blomfeldt@digia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -617,7 +617,7 @@ CFG_EGL=auto
 CFG_EGL_X=auto
 CFG_FONTCONFIG=auto
 CFG_FREETYPE=auto
-CFG_HARFBUZZ=auto
+CFG_HARFBUZZ=qt
 CFG_SQL_AVAILABLE=
 QT_ALL_BUILD_PARTS=" libs tools examples tests "
 QT_DEFAULT_BUILD_PARTS="libs tools examples"
@@ -2357,13 +2357,14 @@ Third Party Libraries:
  +  -system-freetype.... Use the libfreetype provided by the system (enabled if -fontconfig is active).
                          See http://www.freetype.org
 
- *  -no-harfbuzz ....... Do not compile HarfBuzz-NG support.
-    -qt-harfbuzz ....... (experimental) Use HarfBuzz-NG bundled with Qt
+    -no-harfbuzz ....... Do not compile HarfBuzz-NG support.
+ *  -qt-harfbuzz ....... Use HarfBuzz-NG bundled with Qt to do text shaping.
+                         It can still be disabled by setting
+                         the QT_HARFBUZZ environment variable to "old".
+    -system-harfbuzz ... Use HarfBuzz-NG from the operating system
                          to do text shaping. It can still be disabled
-                         by setting QT_HARFBUZZ environment variable to "old".
-    -system-harfbuzz ... (experimental) Use HarfBuzz-NG from the operating system
-                         to do text shaping. It can still be disabled
-                         by setting QT_HARFBUZZ environment variable to "old".
+                         by setting the QT_HARFBUZZ environment variable to "old".
+                         See http://www.harfbuzz.org
 
     -no-openssl ........ Do not compile support for OpenSSL.
  +  -openssl ........... Enable run-time OpenSSL support.
@@ -5301,18 +5302,22 @@ if [ "$CFG_FREETYPE" = "auto" ]; then
 fi
 
 # harfbuzz support
-[ "$XPLATFORM_MAC" = "yes" ] && [ "$CFG_HARFBUZZ" = "auto" ] && CFG_HARFBUZZ=yes
-[ "$CFG_HARFBUZZ" = "auto" ] && CFG_HARFBUZZ=no # disable auto-detection on non-Mac for now
-if [ "$CFG_HARFBUZZ" = "auto" ]; then
-    if compileTest unix/harfbuzz "HarfBuzz"; then
-        CFG_HARFBUZZ=system
-    else
-        CFG_HARFBUZZ=yes
+if [ "$CFG_HARFBUZZ" = "system" ]; then
+    if ! compileTest unix/harfbuzz "HarfBuzz"; then
+        if [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+            echo " HarfBuzz system library support cannot be enabled due to functionality tests!"
+            echo " Turn on verbose messaging (-v) to $0 to see the final report."
+            echo " If you believe this message is in error you may use the continue"
+            echo " switch (-continue) to $0 to continue."
+            exit 101
+        else
+            CFG_HARFBUZZ=qt
+        fi
     fi
 fi
-if [ "$XPLATFORM_MAC" = "yes" -a "$CFG_HARFBUZZ" = "system" ]; then
+if [ "$XPLATFORM_MAC" = "yes" -a "$CFG_HARFBUZZ" != "qt" ]; then
     echo
-    echo "WARNING: AAT is not supported with -system-harfbuzz on Mac OS X."
+    echo "WARNING: On OS X, AAT is supported only with -qt-harfbuzz."
     echo
 fi
 
@@ -6542,7 +6547,7 @@ report_support "  FontConfig ............." "$CFG_FONTCONFIG"
 report_support "  FreeType ..............." "$CFG_FREETYPE" system "system library" yes "bundled copy"
 report_support "  Glib ..................." "$CFG_GLIB"
 report_support "  GTK theme .............." "$CFG_QGTKSTYLE"
-report_support "  HarfBuzz ..............." "$CFG_HARFBUZZ"
+report_support "  HarfBuzz ..............." "$CFG_HARFBUZZ" system "system library" qt "bundled copy"
 report_support "  Iconv .................." "$CFG_ICONV"
 report_support "  ICU ...................." "$CFG_ICU"
 report_support "  Image formats:"
