CMake: Disable building Qt with qmake
Print an error message when configure is passed the -qmake option.
The only supported way to build Qt now is with CMake.

This means the CMakeLists.txt files are the source of truth now, and
pro2cmake will not have to be used anymore.
The .pro files can be removed at a later time.

The same is true for configure.cmake files. They are the authoritative
source, and the configure.json files will be removed at a later time.

Task-number: QTBUG-88741
Change-Id: Ia9de4c1411978b40b13e9b982977e7818164c984
Reviewed-by: Joerg Bornemann <joerg.bornemann@qt.io>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -920,6 +920,12 @@ else
 fi
 }
 
+printQmakeBuildErrorAndExit()
+{
+    echo >&2 "ERROR: You cannot configure Qt 6 with qmake anymore. Please configure with -cmake instead."
+    exit 1
+}
+
 checkTopLevelBuild "$@"
 parseCommandline "$@"
 handleHelp
@@ -945,6 +951,7 @@ if [ "$BUILD_WITH_CMAKE" = "yes" ]; then
 
     cmake "-DOPTFILE=$optfilename" $top_level_arg -P "$relpath/cmake/QtProcessConfigureArgs.cmake"
 else
+    printQmakeBuildErrorAndExit
     findPerl
     findAwk
     findMake
