-device: Use $1 instead of $VAL
$VAL just happens to work in resolveDeviceMkspec because it is
set in the parent shell environment when the function is called.

Change-Id: I67350f2a9e790cc7eca2a73ef6a4a0d7f09b8d3c
Reviewed-by: Sean Harmer <sean.harmer@kdab.com>
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@nokia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -252,15 +252,15 @@ DeviceVar()
 
 resolveDeviceMkspec()
 {
-    result=$(find "$relpath/mkspecs/devices/" -type d -name "*$VAL*" | sed "s,^$relpath/mkspecs/,,")
+    result=$(find "$relpath/mkspecs/devices/" -type d -name "*$1*" | sed "s,^$relpath/mkspecs/,,")
     match_count=$(echo "$result" | wc -w)
     if [ "$match_count" -gt 1 ]; then
-        echo >&2 "Error: Multiple matches for device '$VAL'. Candidates are:"
+        echo >&2 "Error: Multiple matches for device '$1'. Candidates are:"
         tabbed_result=$(echo "$result" | sed "s,^,    ,")
         echo >&2 "$tabbed_result"
         echo "undefined"
     elif [ "$match_count" -eq 0 ]; then
-        echo >&2 "Error: No device matching '$VAL'"
+        echo >&2 "Error: No device matching '$1'"
         echo "undefined"
     else
         echo "$result"
