If -xcb is passed and we can't enable xcb, die
Needed to resolve issue QTBUG-21486

Change-Id: I5493cfa73f0433fda60fb0dd850380021e13b928
Reviewed-on: http://codereview.qt-project.org/5944
Reviewed-by: Qt Sanity Bot <qt_sanity_bot@ovi.com>
Reviewed-by: Rohan McGovern <rohan.mcgovern@nokia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6293,6 +6293,12 @@ if [ "$PLATFORM_QPA" = "yes" ]; then
                 QT_CONFIG="$QT_CONFIG xcb-xlib"
             fi
         else
+            if [ "$CFG_XCB" = "yes" ]; then
+                echo "The XCB test failed!"
+                echo " You might need to install dependency packages."
+                echo " See src/plugins/platforms/xcb/README."
+                exit 1
+            fi
             CFG_XCB=no
         fi
     fi
