Run non-xcb X tests also with -no-xcb
Passing -no-xcb disables xcb and related configuration tests
completely so for example QT_NO_XRENDER is not defined.  This results
in linker errors in glxconvenience with -no-xcb since the XRender
calls are compiled in without linking to the library.

The XRender, XInput and such tests are not strictly xcb related and
may be used from elsewhere, for example glxconvenience which has
nothing to do with xcb. Therefore these tests are moved in configure
so that they are run even when xcb is disabled.

Task-number: QTBUG-35644
Change-Id: I77871612ea5f6711ecafd8ca53aac6c516c19e2e
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@digia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5120,6 +5120,42 @@ if compileTest x11/xlib "XLib"; then
     QT_CONFIG="$QT_CONFIG xlib"
 fi
 
+# auto-detect Xrender support
+if [ "$CFG_XRENDER" != "no" ]; then
+    if compileTest x11/xrender "Xrender"; then
+        CFG_XRENDER=yes
+        QT_CONFIG="$QT_CONFIG xrender"
+    else
+        if [ "$CFG_XRENDER" = "yes" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+            echo "Xrender support cannot be enabled due to functionality tests!"
+            echo " Turn on verbose messaging (-v) to $0 to see the final report."
+            echo " If you believe this message is in error you may use the continue"
+            echo " switch (-continue) to $0 to continue."
+            exit 101
+        else
+            CFG_XRENDER=no
+        fi
+    fi
+fi
+
+# auto-detect XInput2 support
+if [ "$CFG_XINPUT2" != "no" ]; then
+    if compileTest x11/xinput2 "XInput2"; then
+        CFG_XINPUT2=yes
+        CFG_XINPUT=no
+    else
+        if [ "$CFG_XINPUT2" = "yes" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+            echo "XInput2 support cannot be enabled due to functionality tests!"
+            echo " Turn on verbose messaging (-v) to $0 to see the final report."
+            echo " If you believe this message is in error you may use the continue"
+            echo " switch (-continue) to $0 to continue."
+            exit 101
+        else
+            CFG_XINPUT2=no
+        fi
+    fi
+fi
+
 if [ "$CFG_XCB" != "no" ]; then
     if [ -n "$PKG_CONFIG" ] && $PKG_CONFIG --exists "xcb >= 1.5" 2>/dev/null; then
         QMAKE_CFLAGS_XCB="`$PKG_CONFIG --cflags xcb 2>/dev/null`"
@@ -5177,42 +5213,6 @@ if [ "$CFG_XCB" != "no" ]; then
         if [ "$CFG_SM" != "no" ] && [ -n "$PKG_CONFIG" ]; then
             if $PKG_CONFIG --exists "sm" 2>/dev/null && $PKG_CONFIG --exists "ice" 2>/dev/null; then
                 QT_CONFIG="$QT_CONFIG xcb-sm"
-            fi
-        fi
-
-        # auto-detect Xrender support
-        if [ "$CFG_XRENDER" != "no" ]; then
-            if compileTest x11/xrender "Xrender"; then
-                CFG_XRENDER=yes
-                QT_CONFIG="$QT_CONFIG xrender"
-            else
-                if [ "$CFG_XRENDER" = "yes" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
-                    echo "Xrender support cannot be enabled due to functionality tests!"
-                    echo " Turn on verbose messaging (-v) to $0 to see the final report."
-                    echo " If you believe this message is in error you may use the continue"
-                    echo " switch (-continue) to $0 to continue."
-                    exit 101
-                else
-                    CFG_XRENDER=no
-                fi
-            fi
-        fi
-
-        # auto-detect XInput2 support. Needed by xcb too.
-        if [ "$CFG_XINPUT2" != "no" ]; then
-            if compileTest x11/xinput2 "XInput2"; then
-                CFG_XINPUT2=yes
-                CFG_XINPUT=no
-            else
-                if [ "$CFG_XINPUT2" = "yes" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
-                    echo "XInput2 support cannot be enabled due to functionality tests!"
-                    echo " Turn on verbose messaging (-v) to $0 to see the final report."
-                    echo " If you believe this message is in error you may use the continue"
-                    echo " switch (-continue) to $0 to continue."
-                    exit 101
-                else
-                    CFG_XINPUT2=no
-                fi
             fi
         fi
     else
