run syncqt only for builds from git
the logic in the configures was even trying to express that, only that
nowadays we always ship syncqt, so the tests were kinda pointless.

this frees us from the perl dependency for non-developer builds of
packaged modules (except for webkit, which needs almost every scripting
language on earth anyway).

obviously, this requires that the packaging scripts run syncqt in the
source dir before tarring up the sources. note that for repositories
other than qtbase, the -version argument needs to be passed to syncqt.

Task-number: QTBUG-29465
Change-Id: Ic929ab17a5de4b30fbf48b3aa9bfa3b4d2ef37d6
Reviewed-by: Joerg Bornemann <joerg.bornemann@digia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2389,13 +2389,6 @@ fi
 if [ "$OPT_SHADOW" = "yes" ]; then
     echo "Preparing build tree..."
 
-    if [ -z "$PERL" ]; then
-        echo
-        echo "You need perl in your PATH to make a shadow build."
-        echo "Cannot proceed."
-        exit 1
-    fi
-
     [ -d "$outpath/bin" ] || mkdir -p "$outpath/bin"
 
     # save a pre-existing mkspecs/modules dir
@@ -3895,7 +3888,14 @@ fi
 # -----------------------------------------------------------------------------
 
 # symlink includes
-if [ -n "$PERL" ] && [ -x "$relpath/bin/syncqt.pl" ]; then
+if [ -e "$relpath/.git" ]; then
+    if [ -z "$PERL" ]; then
+        echo
+        echo "You need perl in your PATH to make a build from GIT."
+        echo "Cannot proceed."
+        exit 1
+    fi
+
     "$relpath/bin/syncqt.pl" -minimal -module QtCore "$relpath" || exit 1
 fi
 
@@ -4028,6 +4028,11 @@ if true; then ###[ '!' -f "$outpath/bin/qmake" ];
 
         echo "BUILD_PATH = $adjoutpath" >> "$mkfile"
         echo "SOURCE_PATH = $adjrelpath" >> "$mkfile"
+        if [ -e "$relpath/.git" ]; then
+            echo 'INC_PATH = $(BUILD_PATH)/include' >> "$mkfile"
+        else
+            echo 'INC_PATH = $(SOURCE_PATH)/include' >> "$mkfile"
+        fi
         echo "QMAKESPEC = $adjqmakespec" >> "$mkfile"
         echo "QT_VERSION = $QT_VERSION" >> "$mkfile"
         echo "EXTRA_CFLAGS = $EXTRA_CFLAGS" >> "$mkfile"
