complain about various invalid configuration attempts
Task-number: QTBUG-56049
Change-Id: Id5eeb014c2b88195d2d14566a62dcb9185206b37
Reviewed-by: Jake Petroules <jake.petroules@qt.io>
Reviewed-by: Joerg Bornemann <joerg.bornemann@qt.io>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -82,6 +82,11 @@ if [ x"$1" = x"-top-level" ]; then
     relpathMangled=`dirname "$relpath"`
     outpathPrefix=../
     shift
+else
+    if [ -f ../.qmake.super ]; then
+        echo >&2 "ERROR: You cannot configure qtbase separately within a top-level build."
+        exit 1
+    fi
 fi
 
 OPT_CMDLINE=  # expanded version for the script
