Support logging direct to syslog, if enabled.
[ChangeLog][QtCore][Logging] Systems with syslog may now pass -syslog to
configure to send logging output to syslog.

Change-Id: I80d58ee6e70d8deb2409fc666e7e7f2d7f52b8e1
Reviewed-by: Kai Koehne <kai.koehne@theqtcompany.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -621,6 +621,7 @@ CFG_XFIXES=runtime
 CFG_ZLIB=auto
 CFG_MTDEV=auto
 CFG_JOURNALD=no
+CFG_SYSLOG=no
 CFG_SQLITE=qt
 CFG_GIF=auto
 CFG_PNG=yes
@@ -1700,6 +1701,13 @@ while [ "$#" -gt 0 ]; do
             UNKNOWN_OPT=yes
         fi
         ;;
+    syslog)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            CFG_SYSLOG="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
     sqlite)
         if [ "$VAL" = "system" ]; then
             CFG_SQLITE=system
@@ -2471,6 +2479,9 @@ Third Party Libraries:
 
  +  -no-journald ........ Do not send logging output to journald.
     -journald ........... Send logging output to journald.
+
+ +  -no-syslog .......... Do not send logging output to syslog.
+    -syslog ............. Send logging output to syslog.
 
     -no-gif ............. Do not compile GIF reading support.
 
@@ -4553,6 +4564,23 @@ if [ "$CFG_JOURNALD" != "no" ]; then
             exit 101
         else
             CFG_JOURNALD=no
+        fi
+    fi
+fi
+
+if [ "$CFG_SYSLOG" != "no" ]; then
+    if compileTest unix/syslog "syslog"; then
+        CFG_SYSLOG=yes
+        QMAKE_CONFIG="$QMAKE_CONFIG syslog"
+    else
+        if [ "$CFG_SYSLOG" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+            echo "syslog support cannot be enabled due to functionality tests!"
+            echo " Turn on verbose messaging (-v) to $0 to see the final report."
+            echo " If you believe this message is in error you may use the continue"
+            echo " switch (-continue) to $0 to continue."
+            exit 101
+        else
+            CFG_SYSLOG=no
         fi
     fi
 fi
@@ -7078,8 +7106,10 @@ report_support "  Image formats:"
 report_support_plugin "    GIF .................." "$CFG_GIF" qt QtGui
 report_support_plugin "    JPEG ................." "$CFG_JPEG" "$CFG_LIBJPEG" QtGui
 report_support_plugin "    PNG .................." "$CFG_PNG" "$CFG_LIBPNG" QtGui
-report_support "  journald ..............." "$CFG_JOURNALD"
 report_support "  libinput................" "$CFG_LIBINPUT"
+report_support "  Logging backends:"
+report_support "    journald ..............." "$CFG_JOURNALD"
+report_support "    syslog   ..............." "$CFG_SYSLOG"
 report_support "  mtdev .................." "$CFG_MTDEV" yes "system library"
 report_support "  Networking:"
 [ "$XPLATFORM_MAC" = "yes" ] && \
@@ -7169,12 +7199,12 @@ if [ "$CFG_OPENSSL" = "linked" ] && [ "$OPENSSL_LIBS" = "" ]; then
     echo "For example:"
     echo "    OPENSSL_LIBS='-L/opt/ssl/lib -lssl -lcrypto' ./configure -openssl-linked"
 fi
-if [ "$CFG_JOURNALD" = "yes" ] || [ "$CFG_SLOG2" = "yes" ]; then
+if [ "$CFG_JOURNALD" = "yes" ] || [ "$CFG_SYSLOG" = "yes" ] || [ "$CFG_SLOG2" = "yes" ]; then
     echo
-    echo "NOTE: journald or slog2 integration is enabled."
+    echo "NOTE: journald, syslog or slog2 integration is enabled."
     echo "If your users intend on developing applications against this build,"
     echo "ensure that the IDEs they use either set QT_LOGGING_TO_CONSOLE to 1"
-    echo "or the IDE is able to read the logged output from journald or slog2."
+    echo "or the IDE is able to read the logged output from journald, syslog or slog2."
 fi
 if [ "$CFG_XKBCOMMON" = "qt" ] && [ "$CFG_XKB_CONFIG_ROOT" = "not found" ]; then
     echo
